void malloc() {}
void calloc() {}
void realloc() {}
void free() {}

void open() {}
void creat() {}
void close() {}

void read() {}
void write() {}
void lseek() {}

void stat() {}
void fstat() {}

void rename() {}
void truncate() {}
void unlink() {}

void mkdir() {}
void rmdir() {}

void opendir() {}
void readdir() {}
void closedir() {}

void low_call_direct() {}

void low_set_timeout() {}
void low_clear_timeout() {}

void low_add_stash() {}
void low_remove_stash() {}
void low_push_stash() {}

void low_push_buffer() {}
void low_call_next_tick() {}

void duk_base64_decode() {}
void duk_base64_encode() {}
void duk_buffer_to_string() {}
void duk_call() {}
void duk_call_method() {}
void duk_call_prop() {}
void duk_char_code_at() {}
void duk_check_type() {}
void duk_check_type_mask() {}
void duk_components_to_time() {}
void duk_concat() {}
void duk_copy() {}
void duk_decode_string() {}
void duk_def_prop() {}
void duk_del_prop() {}
void duk_del_prop_index() {}
void duk_del_prop_literal_raw() {}
void duk_del_prop_lstring() {}
void duk_del_prop_string() {}
void duk_dup() {}
void duk_dup_top() {}
void duk_enum() {}
void duk_equals() {}
void duk_error_raw() {}
void duk_freeze() {}
void duk_get_boolean() {}
void duk_get_boolean_default() {}
void duk_get_buffer_data() {}
void duk_get_buffer_data_default() {}
void duk_get_c_function() {}
void duk_get_c_function_default() {}
void duk_get_finalizer() {}
void duk_get_int() {}
void duk_get_int_default() {}
void duk_get_length() {}
void duk_get_lstring() {}
void duk_get_lstring_default() {}
void duk_get_now() {}
void duk_get_number() {}
void duk_get_number_default() {}
void duk_get_pointer() {}
void duk_get_pointer_default() {}
void duk_get_prop() {}
void duk_get_prop_desc() {}
void duk_get_prop_index() {}
void duk_get_prop_literal_raw() {}
void duk_get_prop_lstring() {}
void duk_get_prop_string() {}
void duk_get_prototype() {}
void duk_get_string() {}
void duk_get_string_default() {}
void duk_get_top() {}
void duk_get_top_index() {}
void duk_get_type() {}
void duk_get_type_mask() {}
void duk_get_uint() {}
void duk_get_uint_default() {}
void duk_has_prop() {}
void duk_has_prop_index() {}
void duk_has_prop_literal_raw() {}
void duk_has_prop_lstring() {}
void duk_has_prop_string() {}
void duk_hex_decode() {}
void duk_hex_encode() {}
void duk_insert() {}
void duk_instanceof() {}
void duk_is_array() {}
void duk_is_boolean() {}
void duk_is_buffer_data() {}
void duk_is_c_function() {}
void duk_is_constructable() {}
void duk_is_constructor_call() {}
void duk_is_function() {}
void duk_is_nan() {}
void duk_is_null() {}
void duk_is_number() {}
void duk_is_object() {}
void duk_is_pointer() {}
void duk_is_string() {}
void duk_is_symbol() {}
void duk_is_undefined() {}
void duk_is_valid_index() {}
void duk_join() {}
void duk_json_decode() {}
void duk_json_encode() {}
void duk_map_string() {}
void duk_new() {}
void duk_next() {}
void duk_normalize_index() {}
void duk_pop() {}
void duk_pop_2() {}
void duk_pop_3() {}
void duk_pop_n() {}
void duk_push_array() {}
void duk_push_boolean() {}
void duk_push_c_function() {}
void duk_push_current_function() {}
void duk_push_error_object_raw() {}
void duk_push_false() {}
void duk_push_int() {}
void duk_push_literal_raw() {}
void duk_push_lstring() {}
void duk_push_nan() {}
void duk_push_new_target() {}
void duk_push_null() {}
void duk_push_number() {}
void duk_push_object() {}
void duk_push_pointer() {}
void duk_push_proxy() {}
void duk_push_sprintf() {}
void duk_push_string() {}
void duk_push_this() {}
void duk_push_true() {}
void duk_push_uint() {}
void duk_push_undefined() {}
void duk_put_function_list() {}
void duk_put_number_list() {}
void duk_put_prop() {}
void duk_put_prop_index() {}
void duk_put_prop_literal_raw() {}
void duk_put_prop_lstring() {}
void duk_put_prop_string() {}
void duk_random() {}
void duk_remove() {}
void duk_replace() {}
void duk_samevalue() {}
void duk_seal() {}
void duk_set_finalizer() {}
void duk_set_length() {}
void duk_set_prototype() {}
void duk_set_top() {}
void duk_strict_equals() {}
void duk_substring() {}
void duk_swap() {}
void duk_swap_top() {}
void duk_throw_raw() {}
void duk_time_to_components() {}
void duk_to_boolean() {}
void duk_to_int() {}
void duk_to_int32() {}
void duk_to_lstring() {}
void duk_to_null() {}
void duk_to_number() {}
void duk_to_object() {}
void duk_to_pointer() {}
void duk_to_primitive() {}
void duk_to_string() {}
void duk_to_uint() {}
void duk_to_uint16() {}
void duk_to_uint32() {}
void duk_to_undefined() {}
void duk_trim() {}